In [3]:
!pip install pandas_datareader --quiet

WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\pablo\anaconda3\python.exe -m pip install --upgrade pip' command.

In [23]:
import urllib.request
import pandas as pd
from pandas_datareader import data
import requests

data_inicial = "2/26/2021"
tipoPessoa = "1"
modalidade = "218" 
encargo = "101"


import urllib.request
import pandas as pd
from pandas_datareader import data
csv_url = f'https://www.bcb.gov.br/api/relatorio/pt-br/contaspub?path=conteudo/txcred/Reports/TaxasCredito-Consolidadas-porTaxasAnuais-Historico.rdl&nome=RelatorioHist%C3%B3rico%20Posterior%20a%2001/01/2012&parametros=tipoPessoa:{tipoPessoa};modalidade:{modalidade};encargo:{encargo};periodoInicial:{data_inicial}%2012:00:00%20AM;&exportar=CSV'
urllib.request.urlretrieve(csv_url, 'MSFT.csv')

('MSFT.csv', <http.client.HTTPMessage at 0x1e6c475e8b0>)

In [24]:
df = pd.read_csv("MSFT.CSV",  index_col="POSICAO", skiprows=3)

df.head()

                                IF_NM TAXAS_MENSAIS TAXAS_ANUAIS
POSICAO
1                FINANC ALFA S.A. CFI          1,18        15,10
2                   PARATI - CFI S.A.          1,27        16,34
3                   BANCO SICOOB S.A.          1,29        16,56
4        BCO COOPERATIVO SICREDI S.A.          1,30        16,82
5                         BANCO INTER          1,31        16,90

In [25]:
!pip install xlwings --upgrade --quiet

WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\pablo\anaconda3\python.exe -m pip install --upgrade pip' command.

In [26]:
import xlwings as xw

In [27]:
df

                                     IF_NM TAXAS_MENSAIS TAXAS_ANUAIS
POSICAO
1                     FINANC ALFA S.A. CFI          1,18        15,10
2                        PARATI - CFI S.A.          1,27        16,34
3                        BANCO SICOOB S.A.          1,29        16,56
4             BCO COOPERATIVO SICREDI S.A.          1,30        16,82
5                              BANCO INTER          1,31        16,90
6                 BCO DO ESTADO DO RS S.A.          1,35        17,42
7                         BCO CREFISA S.A.          1,36        17,55
8                          BANCO BARI S.A.          1,38        17,81
9                         BCO CETELEM S.A.          1,42        18,44
10                          BCO SAFRA S.A.          1,44        18,69
11                    BCO DA AMAZONIA S.A.          1,47        19,14
12                            ZEMA CFI S/A          1,47        19,18
13                         PARANA BCO S.A.          1,51        19,70
14                          FACTA S.A. CFI          1,53        19,93
15                 CAIXA ECONOMICA FEDERAL          1,53        19,93
16                      BCO DO BRASIL S.A.          1,55        20,33
17                      ITAÃš UNIBANCO S.A.          1,56        20,35
18               BCO BRADESCO FINANC. S.A.          1,57        20,52
19                       BCO BRADESCO S.A.          1,58        20,66
20             BCO SANTANDER (BRASIL) S.A.          1,60        20,92
21                  BCO DO EST. DE SE S.A.          1,61        21,18
22                        BCO DAYCOVAL S.A          1,62        21,33
23                       BCO BANESTES S.A.          1,65        21,69
24                        BCO AGIBANK S.A.          1,66        21,87
25              BANCO ITAÃš CONSIGNADO S.A.          1,71        22,51
26          BCO DO NORDESTE DO BRASIL S.A.          1,72        22,73
27                            BCO BMG S.A.          1,74        23,00
28                     GAZINCRED S.A. SCFI          1,76        23,29
29                       CREDIARE CFI S.A.          1,77        23,45
30            BCO MERCANTIL DO BRASIL S.A.          1,78        23,62
31                           BCO C6 CONSIG          1,81        23,99
32                               BANCO PAN          1,83        24,24
33           MERCANTIL BRASIL FIN S.A. CFI          1,83        24,34
34       VIA CERTA FINANCIADORA S.A. - CFI          1,83        24,36
35              BRB - BCO DE BRASILIA S.A.          1,85        24,64

In [28]:
# Visualizar dataset no excel

xw.view(df)