In [5]:
!pip install pandas_datareader --quiet

WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\pablo\anaconda3\python.exe -m pip install --upgrade pip' command.

In [7]:
import urllib.request
import pandas as pd
from pandas_datareader import data
csv_url = 'https://www.bcb.gov.br/api/relatorio/pt-br/contaspub?path=conteudo/txcred/Reports/TaxasCredito-Consolidadas-porTaxasAnuais-Historico.rdl&nome=RelatorioHist%C3%B3rico%20Posterior%20a%2001/01/2012&parametros=tipoPessoa:1;modalidade:218;encargo:101;periodoInicial:7/26/2021%2012:00:00%20AM;&exportar=CSV'
urllib.request.urlretrieve(csv_url, 'MSFT.csv')

('MSFT.csv', <http.client.HTTPMessage at 0x1f06b3e5460>)

In [8]:
df = pd.read_csv("MSFT.CSV",  index_col="POSICAO", skiprows=3)

df.head()

                         IF_NM TAXAS_MENSAIS TAXAS_ANUAIS
POSICAO
1                  BANCO INTER          1,17        14,91
2            BANCO SICOOB S.A.          1,17        14,97
3        CCB BRASIL S.A. - CFI          1,26        16,24
4             BCO CETELEM S.A.          1,28        16,43
5         FINANC ALFA S.A. CFI          1,29        16,56

In [9]:
!pip install xlwings --upgrade --quiet

WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\pablo\anaconda3\python.exe -m pip install --upgrade pip' command.

In [10]:
import xlwings as xw

In [12]:
df

                                     IF_NM TAXAS_MENSAIS TAXAS_ANUAIS
POSICAO
1                              BANCO INTER          1,17        14,91
2                        BANCO SICOOB S.A.          1,17        14,97
3                    CCB BRASIL S.A. - CFI          1,26        16,24
4                         BCO CETELEM S.A.          1,28        16,43
5                     FINANC ALFA S.A. CFI          1,29        16,56
6             BCO COOPERATIVO SICREDI S.A.          1,30        16,77
7                         BCO DAYCOVAL S.A          1,40        18,22
8                 BCO DO ESTADO DO RS S.A.          1,41        18,32
9                          PARANA BCO S.A.          1,43        18,57
10                 CAIXA ECONOMICA FEDERAL          1,45        18,85
11                          BCO SAFRA S.A.          1,46        18,96
12                       PARATI - CFI S.A.          1,50        19,51
13               BCO BRADESCO FINANC. S.A.          1,51        19,70
14             BCO SANTANDER (BRASIL) S.A.          1,55        20,27
15                       BCO BRADESCO S.A.          1,55        20,32
16                    BCO DA AMAZONIA S.A.          1,58        20,70
17                        BCO CREFISA S.A.          1,58        20,72
18                            BCO BMG S.A.          1,60        20,98
19                  BCO DO EST. DE SE S.A.          1,62        21,22
20                      BCO DO BRASIL S.A.          1,62        21,24
21                        BCO AGIBANK S.A.          1,65        21,66
22       VIA CERTA FINANCIADORA S.A. - CFI          1,65        21,69
23              BANCO ITAÚ CONSIGNADO S.A.          1,65        21,69
24                       BCO BANESTES S.A.          1,67        21,98
25                           HS FINANCEIRA          1,70        22,44
26                           BCO C6 CONSIG          1,73        22,84
27                      ITAÚ UNIBANCO S.A.          1,73        22,90
28                       CREDIARE CFI S.A.          1,74        22,92
29                     GAZINCRED S.A. SCFI          1,75        23,12
30                            ZEMA CFI S/A          1,78        23,58
31            BCO MERCANTIL DO BRASIL S.A.          1,79        23,66
32                               BANCO PAN          1,80        23,93
33          BCO DO NORDESTE DO BRASIL S.A.          1,86        24,70

In [13]:
# Visualizar dataset no excel

xw.view(df)